BEGIN;

CREATE SCHEMA IF NOT EXISTS dti AUTHORIZATION dti_admin;
GRANT ALL ON SCHEMA dti TO dti_admin;
GRANT USAGE ON SCHEMA dti TO dti_viewer;
GRANT USAGE ON SCHEMA dti TO dti_user;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE  ON ALL TABLES IN SCHEMA dti TO dti_user;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA dti TO dti_user;

COMMENT ON SCHEMA dti
  IS 'DCAE Topology Interface Schema';
COMMIT;
