BEGIN;
ALTER DEFAULT PRIVILEGES
    IN SCHEMA dti
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dti_user;
ALTER DEFAULT PRIVILEGES
    IN SCHEMA dti
    GRANT SELECT ON TABLES TO dti_viewer;
COMMIT;

