CREATE TABLE IF NOT EXISTS dti.rt_dvs_switch
(
    SWITCH_NAME         VARCHAR(40) NOT NULL,
    VCENTER_URL         VARCHAR(200) NOT NULL,
    RESOURCE_VERSION    VARCHAR(25),
    UPDATED_ON          VARCHAR(20),
    PRIMARY KEY (SWITCH_NAME)
);
