CREATE TABLE IF NOT EXISTS dti.rt_forwarder
(
    SEQUENCE                  INTEGER NOT NULL,
    FORWARDER_ROLE            VARCHAR(50),
    RESOURCE_VERSION          VARCHAR(25),
    FORWARDING_PATH_ID        VARCHAR(150) NOT NULL,
    UPDATED_ON                VARCHAR(20),
    PRIMARY KEY (SEQUENCE,FORWARDING_PATH_ID)
);
