CREATE TABLE IF NOT EXISTS dti.rt_generic_vnf
(
    VNF_ID                       VARCHAR(150) NOT NULL,
    VNF_NAME                     VARCHAR(100) NOT NULL,
    VNF_NAME2                    VARCHAR(256),
    VNF_TYPE                     VARCHAR(250) NOT NULL,
    SERVICE_ID                   VARCHAR(150),
    REGIONAL_RESOURCE_ZONE       VARCHAR(20),
    PROV_STATUS                  VARCHAR(20),
    OPERATIONAL_STATUS           VARCHAR(25),
    EQUIPMENT_ROLE               VARCHAR(20),
    ORCHESTRATION_STATUS         VARCHAR(25),
    HEAT_STACK_ID                VARCHAR(150),
    MSO_CATALOG_KEY              VARCHAR(40),
    MANAGEMENT_OPTION            VARCHAR(20),
    IPV4_OAM_ADDRESS             VARCHAR(20),
    IPV4_LOOPBACK0_ADDRESS       VARCHAR(20),
    NM_LANV6_ADDRESS             VARCHAR(45),
    MANAGEMENT_V6_ADDRESS        VARCHAR(45),
    VCPU                         BIGINT,
    VCPU_UNITS                   VARCHAR(10),
    VMEMORY                      BIGINT,
    VMEMORY_UNITS                VARCHAR(10),
    VDISK                        BIGINT,
    VDISK_UNITS                  VARCHAR(80),
    IN_MAINT                     VARCHAR(1),
    IS_CLOSED_LOOP_DISABLED      VARCHAR(1),
    RESOURCE_VERSION             VARCHAR(25),
    SUMMARY_STATUS               VARCHAR(250),
    ENCRYPTED_ACCESS_FLAG        VARCHAR(1),
    MODEL_INVARIANT_ID           VARCHAR(150),
    MODEL_VERSION_ID             VARCHAR(100),
    MODEL_CUSTOMIZATION_ID       VARCHAR(150),
    WIDGET_MODEL_ID              VARCHAR(150),
    WIDGET_MODEL_VERSION         VARCHAR(25),
    AS_NUMBER                    VARCHAR(20),
    REGIONAL_RESOURCE_SUBZONE    VARCHAR(50),
    NF_TYPE                      VARCHAR(50),
    NF_ROLE                      VARCHAR(50),
    NF_FUNCTION                  VARCHAR(50),
    NF_NAMING_CODE               VARCHAR(50),
    SELFLINK                     VARCHAR(4000),
    IPV4_OAM_GATEWAY_ADDRESS     VARCHAR(20),
    IPV4_OAM_GATEWAY_ADDRESS_PREFIX_LENGTH VARCHAR(20),
    VLAN_ID_OUTER                VARCHAR(100),
    NM_PROFILE_NAME              VARCHAR(100),
    UPDATED_ON                   VARCHAR(20),
    PRIMARY KEY (VNF_ID)
);
