CREATE TABLE IF NOT EXISTS dti.rt_model_ver
(
    MODEL_VERSION_ID          VARCHAR(100) NOT NULL,
    MODEL_NAME                VARCHAR(100) NOT NULL,
    MODEL_VERSION             VARCHAR(25) NOT NULL,
    MODEL_DESCRIPTION         VARCHAR(2500),
    DISTRIBUTION_STATUS       VARCHAR(50),
    RESOURCE_VERSION          VARCHAR(25),
    MODEL_INVARIANT_ID        VARCHAR(150) NOT NULL,
    UPDATED_ON                VARCHAR(20),
    PRIMARY KEY (MODEL_VERSION_ID,MODEL_INVARIANT_ID)
);
