CREATE TABLE IF NOT EXISTS dti.rt_service_subscription
(
    SERVICE_TYPE          VARCHAR(100) NOT NULL,
    RESOURCE_VERSION      VARCHAR(25),
    GLOBAL_CUSTOMER_ID    VARCHAR(50) NOT NULL,
    UPDATED_ON            VARCHAR(20),
    PRIMARY KEY (SERVICE_TYPE,GLOBAL_CUSTOMER_ID)
);
