BEGIN;
\i sql/table/community_string.sql
\i sql/table/dcae_event.sql
\i sql/table/rt_allotted_resource.sql
\i sql/table/rt_availability_zone.sql
\i sql/table/rt_cloud_region.sql
\i sql/table/rt_cloud_vip_ipv4_address_list.sql
\i sql/table/rt_cloud_vip_ipv6_address_list.sql
\i sql/table/rt_complex.sql
\i sql/table/rt_cp.sql
\i sql/table/rt_customer.sql
\i sql/table/rt_dvs_switch.sql
\i sql/table/rt_flavor.sql
\i sql/table/rt_forwarder.sql
\i sql/table/rt_forwarding_path.sql
\i sql/table/rt_generic_vnf.sql
\i sql/table/rt_image.sql
\i sql/table/rt_l3_network.sql
\i sql/table/rt_l3interface_ipv4addresslist.sql
\i sql/table/rt_l3interface_ipv6addresslist.sql
\i sql/table/rt_l_interface.sql
\i sql/table/rt_lag_interface.sql
\i sql/table/rt_lag_link.sql
\i sql/table/rt_line_of_business.sql
\i sql/table/rt_logical_link.sql
\i sql/table/rt_metadatum.sql
\i sql/table/rt_model.sql
\i sql/table/rt_model_ver.sql
\i sql/table/rt_network_profile.sql
\i sql/table/rt_nos_server.sql
\i sql/table/rt_oam_network.sql
\i sql/table/rt_operational_environment.sql
\i sql/table/rt_owning_entity.sql
\i sql/table/rt_p_interface.sql
\i sql/table/rt_physical_link.sql
\i sql/table/rt_platform.sql
\i sql/table/rt_pnf.sql
\i sql/table/rt_port_group.sql
\i sql/table/rt_project.sql
\i sql/table/rt_pserver.sql
\i sql/table/rt_relationship_list.sql
\i sql/table/rt_seeding_manager.sql
\i sql/table/rt_service.sql
\i sql/table/rt_service_capability.sql
\i sql/table/rt_service_instance.sql
\i sql/table/rt_service_subscription.sql
\i sql/table/rt_sriov_pf.sql
\i sql/table/rt_sriov_vf.sql
\i sql/table/rt_subnet.sql
\i sql/table/rt_tenant.sql
\i sql/table/rt_vce.sql
\i sql/table/rt_vf_module.sql
\i sql/table/rt_virtual_data_center.sql
\i sql/table/rt_vlan.sql
\i sql/table/rt_vnf_image.sql
\i sql/table/rt_vnfc.sql
\i sql/table/rt_volume.sql
\i sql/table/rt_vpls_pe.sql
\i sql/table/rt_vserver.sql
\i sql/table/rt_zone.sql
\i sql/table/vertica_feed.sql
COMMIT;
