DROP TABLE IF EXISTS dti.vm_fc_vnfc_fc_map CASCADE;

CREATE TABLE dti.vm_fc_vnfc_fc_map
(
        VM_FUNC_CODE VARCHAR(4) NOT NULL, 
	VNFC_FUNC_CODE VARCHAR(3) NOT NULL, 
	VM_SEQUENCE_NUMBER VARCHAR(50) NOT NULL
);


