
DROP TABLE IF EXISTS dti.vnodelist CASCADE;

CREATE SEQUENCE IF NOT EXISTS VNODELIST_VNODELISTKEY_SEQ;

CREATE TABLE dti.vnodelist
(
        VNODELISTKEY BIGINT DEFAULT NEXTVAL('VNODELIST_VNODELISTKEY_SEQ'),
  	USERID VARCHAR(10) NOT NULL, 
  	VALIDFROM VARCHAR(14) NOT NULL, 
  	VALIDTO VARCHAR(14), 
  	UPDATEDBY VARCHAR(6), 
  	DELETEBY VARCHAR(6), 
  	SENDTOETL VARCHAR(1) NOT NULL, 
  	NODE_NAME VARCHAR(50) NOT NULL, 
  	NODELEVEL VARCHAR(20), 
  	PROV_STATUS VARCHAR(20) NOT NULL, 
  	IN_MAINT VARCHAR(1) NOT NULL, 
  	SERVICE VARCHAR(100) NOT NULL, 
  	FUNC_CODE VARCHAR(4) NOT NULL, 
  	NETWORK VARCHAR(10) NOT NULL, 
  	SERVICE_TYPE VARCHAR(10) NOT NULL, 
  	NODE_TYPE VARCHAR(20) NOT NULL, 
  	NODE_SUB_TYPE VARCHAR(10) NOT NULL, 
  	CLLI VARCHAR(26), 
  	REGION_ZONE VARCHAR(20), 
  	OAMP_IP_ADDR VARCHAR(20) NOT NULL, 
  	TVSP_IP_ADDR VARCHAR(20), 
  	COL_NODE_NAME VARCHAR(20), 
  	COL_IP_ADDR VARCHAR(45), 
  	UUID VARCHAR(150), 
  	FQDN VARCHAR(100), 
  	VNF_PARENT VARCHAR(150), 
  	VS_PARENT VARCHAR(150), 
  	PS_PARENT VARCHAR(150), 
  	MATE_NODE VARCHAR(50), 
  	TENANT_ID VARCHAR(36), 
  	VNFC_FUNC_CODE VARCHAR(3), 
  	DKAT_SERVICE VARCHAR(100) DEFAULT 'NA', 
  	DKAT_NODETYPE VARCHAR(50) DEFAULT 'NA'
);

CREATE UNIQUE INDEX VNODELIST_IDX1 
    ON DTI.VNODELIST (NODE_NAME,SERVICE,VALIDFROM)
;

CREATE INDEX VNODELIST_IDX 
    ON DTI.VNODELIST (NODE_NAME)
;

GRANT SELECT, INSERT, UPDATE, DELETE ON DTI.VNODELIST TO dti_user;
GRANT USAGE, SELECT ON SEQUENCE VNODELIST_VNODELISTKEY_SEQ TO dti_user;


