CREATE TABLE IF NOT EXISTS dti.rt_image
(
    IMAGE_ID               VARCHAR(150) NOT NULL,
    IMAGE_NAME             VARCHAR(100),
    IMAGE_ARCHITECTURE     VARCHAR(50),
    IMAGE_OS_DISTRO        VARCHAR(100),
    IMAGE_OS_VERSION       VARCHAR(50),
    APPLICATION            VARCHAR(40),
    APPLICATION_VENDOR     VARCHAR(50),
    APPLICATION_VERSION    VARCHAR(100),
    IMAGE_SELFLINK	       VARCHAR(4000),
    RESOURCE_VERSION       VARCHAR(25),
    CLOUD_OWNER            VARCHAR(25)  NOT NULL,
    CLOUD_REGION_ID        VARCHAR(20)  NOT NULL,
    UPDATED_ON             VARCHAR(20),
    PRIMARY KEY (IMAGE_ID, CLOUD_OWNER, CLOUD_REGION_ID)
);
