CREATE TABLE IF NOT EXISTS dti.rt_operational_environment
(
    OPERATIONAL_ENVIRONMENT_ID        VARCHAR(150) NOT NULL,
    OPERATIONAL_ENVIRONMENT_NAME      VARCHAR(50) NOT NULL,
    OPERATIONAL_ENVIRONMENT_TYPE      VARCHAR(50) NOT NULL,
    OPERATIONAL_ENVIRONMENT_STATUS    VARCHAR(50) NOT NULL,
    TENANT_CONTEXT                    VARCHAR(50) NOT NULL,
    WORKLOAD_CONTEXT                  VARCHAR(50) NOT NULL,
    RESOURCE_VERSION                  VARCHAR(25),
    UPDATED_ON                        VARCHAR(20),
    PRIMARY KEY (OPERATIONAL_ENVIRONMENT_ID)
);
