CREATE TABLE IF NOT EXISTS dti.rt_sriov_pf
(
    PF_PCI_ID                  VARCHAR(50)    NOT NULL,
    RESOURCE_VERSION           VARCHAR(50)   NULL,
    GRANDPARENT_ENTITY_TYPE    VARCHAR(50)   NOT NULL,
    GRANDPARENT_ENTITY_NAME    VARCHAR(50)   NOT NULL,
    INTERFACE_NAME             VARCHAR(50)   NOT NULL,    
    UPDATED_ON                 VARCHAR(20),
    PRIMARY KEY (PF_PCI_ID, GRANDPARENT_ENTITY_TYPE, GRANDPARENT_ENTITY_NAME, INTERFACE_NAME)
);
