CREATE TABLE IF NOT EXISTS dti.rt_tenant
(
    TENANT_ID           VARCHAR(150 ) NOT NULL,
    TENANT_NAME         VARCHAR(80) NOT NULL,
    TENANT_CONTEXT      VARCHAR(150),
    RESOURCE_VERSION    VARCHAR(25),
    CLOUD_OWNER         VARCHAR(25)  NOT NULL,
    CLOUD_REGION_ID     VARCHAR(20)  NOT NULL,
    UPDATED_ON          VARCHAR(20),
    PRIMARY KEY (TENANT_ID,CLOUD_OWNER,CLOUD_REGION_ID)
);

CREATE INDEX IF NOT EXISTS rt_tenant_idx 
          ON dti.rt_tenant ( TENANT_ID, CLOUD_REGION_ID )
;