CREATE TABLE IF NOT EXISTS dti.narad_instance_group
(
		ID VARCHAR(150)	 NOT NULL PRIMARY KEY,
		INSTANCE_GROUP_ROLE VARCHAR(50),
		MODEL_INVARIANT_ID VARCHAR(150),
		MODEL_VERSION_ID VARCHAR(100),
		DESCRIPTION VARCHAR(500),
		INSTANCE_GROUP_TYPE VARCHAR(50) NOT NULL,
		RESOURCE_VERSION VARCHAR(25),
		INSTANCE_GROUP_NAME VARCHAR(50),
		INSTANCE_GROUP_FUNCTION VARCHAR(50),
		UPDATED_ON                VARCHAR(20)
);
