
CREATE TABLE IF NOT EXISTS dti.narad_card_slot
(
		CHASSIS_NAME VARCHAR(50)	 NOT NULL,
		CARD_SLOT_NAME VARCHAR(50)	 NOT NULL,
		RESOURCE_VERSION VARCHAR(25),
		UPDATED_ON                VARCHAR(20),
		PRIMARY KEY (CHASSIS_NAME, CARD_SLOT_NAME)
);
