CREATE TABLE IF NOT EXISTS dti.narad_port
(
	CHASSIS_NAME VARCHAR(50)	 NOT NULL,
	CARD_SLOT_NAME VARCHAR(50),
	CARD_TYPE VARCHAR(50),
	PLUGGABLE_SLOT_NAME VARCHAR(50),
	PLUGGABLE_TYPE VARCHAR(50),
	PORT_NAME VARCHAR(50) NOT NULL,
	PORT_TYPE VARCHAR(50) NOT NULL,
	PORT_ROLE VARCHAR(50) NOT NULL,
	SPEED_VALUE VARCHAR(25),
	SPEED_UNITS VARCHAR(10),
	RESOURCE_VERSION VARCHAR(25),
	UPDATED_ON VARCHAR(20),
	PRIMARY KEY (CHASSIS_NAME,PORT_NAME)
);
