CREATE TABLE IF NOT EXISTS dti.narad_relationship_list
(
	FROM_NODE_ID	VARCHAR(500)	 NOT NULL,
	TO_NODE_ID	VARCHAR(500)	 NOT NULL,
	RELATED_FROM	VARCHAR(40)	 NOT NULL,
	RELATED_TO	VARCHAR(40)	 NOT NULL,
	RELATED_LINK	VARCHAR(4000),
	RELATIONSHIP_LABEL VARCHAR(100),
	UPDATED_ON                VARCHAR(20),
	PRIMARY KEY (FROM_NODE_ID, TO_NODE_ID, RELATED_FROM, RELATED_TO)
);
