CREATE TABLE IF NOT EXISTS dti.dcae_event
(
    dcae_target_name                           VARCHAR(150) NOT NULL,
    dcae_target_type                           VARCHAR(15)  NOT NULL,
    dcae_service_location                      VARCHAR(50)  NOT NULL,
    dcae_service_action                        VARCHAR(15)  NOT NULL,
    dcae_target_prov_status                    VARCHAR(15)  NOT NULL,
    dcae_service_type                          VARCHAR(150) NULL,
    dcae_target_in_maint                       VARCHAR(5)   NULL,
    dcae_target_is_closed_loop_disabled        VARCHAR(5)   NULL,
    dcae_service_instance_model_invariant_id   VARCHAR(150) NULL,
    dcae_service_instance_model_version_id     VARCHAR(100) NULL,
    dcae_generic_vnf_model_invariant_id        VARCHAR(150) NULL,
    dcae_generic_vnf_model_version_id          VARCHAR(100) NULL,
    dcae_target_service_description            VARCHAR(150) NULL,
    dcae_target_collection                     VARCHAR(5)   NULL,
    dcae_target_collection_ip                  VARCHAR(20)  NULL,
    dcae_snmp_community_string                 VARCHAR(100) NULL,
    dcae_snmp_version                          VARCHAR(20)  NULL,
    dcae_target_cloud_region_id                VARCHAR(20)  NULL,
    dcae_target_cloud_region_version           VARCHAR(10)  NULL,
    event                                      TEXT         NULL,
    aai_additional_info                        TEXT         NULL,
    dcae_event_sent_flag                       VARCHAR(5)   NULL,
    dcae_event_status                          VARCHAR(10)  NULL,
    dcae_event_retry_interval                  VARCHAR(10)  NULL,
    dcae_event_retry_number                    VARCHAR(10)  NULL,
    updated_on                                 VARCHAR(20)  NULL,
    PRIMARY KEY (dcae_target_name, dcae_target_type)
);
