
DROP TABLE IF EXISTS dti.networkelementattributes CASCADE;

CREATE SEQUENCE IF NOT EXISTS NETWORKELEMENTATTRIBUTES_NEATTRKEY_SEQ;

CREATE TABLE dti.networkelementattributes
(
        NEATTRKEY INTEGER DEFAULT NEXTVAL('NETWORKELEMENTATTRIBUTES_NEATTRKEY_SEQ'),
   	USERID VARCHAR(20) NOT NULL, 
   	VALIDFROM VARCHAR(14) NOT NULL, 
   	VALIDTO VARCHAR(14), 
   	UPDATEDBY VARCHAR(6), 
   	DELETEBY VARCHAR(6), 
   	SENDTOETL VARCHAR(1) NOT NULL, 
   	NOTES VARCHAR(4000), 
   	SERVICE VARCHAR(100) NOT NULL, 
   	FUNC_CODE VARCHAR(4) NOT NULL, 
   	NODE_TYPE VARCHAR(20) NOT NULL, 
   	NODE_SUB_TYPE VARCHAR(10) NOT NULL, 
   	NETWORK VARCHAR(10) NOT NULL, 
   	SERVICE_TYPE VARCHAR(10) NOT NULL, 
   	DKAT_SERVICE VARCHAR(100) DEFAULT 'BVOIP' NOT NULL, 
   	DKAT_NODETYPE VARCHAR(50) DEFAULT ' ' NOT NULL
);


CREATE UNIQUE INDEX NETWORKELEMENTATTRIBUTES_IDX1 
    ON DTI.NETWORKELEMENTATTRIBUTES (VALIDFROM, FUNC_CODE, NODE_TYPE, NODE_SUB_TYPE, NETWORK, SERVICE_TYPE)
;

CREATE INDEX NETWORKELEMENTATTRIBUTES_IDX 
    ON DTI.NETWORKELEMENTATTRIBUTES (FUNC_CODE)
;

