CREATE TABLE IF NOT EXISTS dti.rt_allotted_resource
(
    GLOBAL_CUSTOMER_ID      VARCHAR(250) NOT NULL,
    SERVICE_TYPE            VARCHAR(100) NOT NULL,
    SERVICE_INSTANCE_ID     VARCHAR(150) NOT NULL,
    ID                      VARCHAR(150) NOT NULL,
    DESCRIPTION             VARCHAR(500),
    SELFLINK                VARCHAR(4000),
    MODEL_INVARIANT_ID      VARCHAR(150),
    MODEL_VERSION_ID        VARCHAR(150),
    RESOURCE_VERSION        VARCHAR(50),
    ORCHESTRATION_STATUS    VARCHAR(25),
    OPERATIONAL_STATUS      VARCHAR(50),
    TYPE                    VARCHAR(500),
    ROLE                    VARCHAR(150),
    UPDATED_ON              VARCHAR(20),
    PRIMARY KEY (GLOBAL_CUSTOMER_ID,SERVICE_TYPE,SERVICE_INSTANCE_ID,ID)
);
