CREATE TABLE IF NOT EXISTS dti.rt_availability_zone
(
    AVAILABILITY_ZONE_NAME    VARCHAR(50) NOT NULL,
    HYPERVISOR_TYPE           VARCHAR(10) NOT NULL,
    OPERATIONAL_STATUS        VARCHAR(25),
    RESOURCE_VERSION          VARCHAR(25),
    CLOUD_OWNER               VARCHAR(25)  NOT NULL,
    CLOUD_REGION_ID           VARCHAR(20)  NOT NULL,
    UPDATED_ON                VARCHAR(20),
    PRIMARY KEY (AVAILABILITY_ZONE_NAME, CLOUD_OWNER, CLOUD_REGION_ID)
);
