CREATE TABLE IF NOT EXISTS dti.rt_cp
(
    CP_INSTANCE_ID      VARCHAR(150) NOT NULL,
    PORT_ID             INTEGER,
    RESOURCE_VERSION    VARCHAR(25),
    VNFC_NAME           VARCHAR(40) NOT NULL,
    UPDATED_ON          VARCHAR(20),
    PRIMARY KEY (CP_INSTANCE_ID,VNFC_NAME)
);
