CREATE TABLE IF NOT EXISTS dti.rt_customer
(
    GLOBAL_CUSTOMER_ID    VARCHAR(250) NOT NULL,
    SUBSCRIBER_NAME       VARCHAR(250) NOT NULL,
    RESOURCE_VERSION      VARCHAR(25),
    UPDATED_ON            VARCHAR(20),
    PRIMARY KEY (GLOBAL_CUSTOMER_ID)
);
