CREATE TABLE IF NOT EXISTS dti.rt_l3interface_ipv4addresslist
(
    IPV4ADDRESS      		  VARCHAR(20) NOT NULL,
    IPV4PREFIXLENGTH          BIGINT,
    VLAN_ID_INNER             BIGINT,
    VLAN_ID_OUTER             BIGINT, 
    IS_FLOATING               VARCHAR(1),
    RESOURCE_VERSION          VARCHAR(25),
    neutron_network_id        VARCHAR(150),
    neutron_subnet_id         VARCHAR(150),
    PARENT_ENTITY_TYPE        VARCHAR(60),
    PARENT_ENTITY_ID          VARCHAR(250),
    GRANDPARENT_ENTITY_TYPE   VARCHAR(60) NOT NULL,
    GRANDPARENT_ENTITY_ID     VARCHAR(250) NOT NULL,
    CLOUD_REGION_TENANT       VARCHAR(200),
    P_INTERFACE_NAME          VARCHAR(50),
    LAG_INTERFACE_NAME        VARCHAR(40),
    VLAN_INTERFACE            VARCHAR(64),  
    UPDATED_ON                VARCHAR(20),
    PRIMARY KEY (IPV4ADDRESS,GRANDPARENT_ENTITY_ID,PARENT_ENTITY_ID,CLOUD_REGION_TENANT,P_INTERFACE_NAME,LAG_INTERFACE_NAME,VLAN_INTERFACE)
);
