CREATE TABLE IF NOT EXISTS dti.rt_lag_interface
(
    INTERFACE_NAME           VARCHAR(100) NOT NULL,
    INTERFACE_DESCRIPTION    VARCHAR(125),
    RESOURCE_VERSION         VARCHAR(25),
    SPEED_VALUE              BIGINT,
    SPEED_UNITS              VARCHAR(10),
    INTERFACE_ID             VARCHAR(150),
    INTERFACE_ROLE           VARCHAR(100),
    PROV_STATUS              VARCHAR(10),
    IN_MAINT                 VARCHAR(1) NOT NULL DEFAULT 'N',
    PARENT_ENTITY_TYPE       VARCHAR(40) NOT Null,
    PARENT_ENTITY_ID         VARCHAR(100) NOT Null,
    UPDATED_ON               VARCHAR(20),
    PRIMARY KEY (INTERFACE_NAME,PARENT_ENTITY_TYPE,PARENT_ENTITY_ID)
);
