CREATE TABLE IF NOT EXISTS dti.rt_model
(
    MODEL_INVARIANT_ID    VARCHAR(150) NOT NULL,
    MODEL_TYPE            VARCHAR(50) NOT NULL,
    RESOURCE_VERSION      VARCHAR(25),
    UPDATED_ON            VARCHAR(20),
    PRIMARY KEY (MODEL_INVARIANT_ID)
);
