CREATE TABLE IF NOT EXISTS dti.rt_metadatum
(
    METANAME              VARCHAR(100)    NOT NULL,
    METAVAL               VARCHAR(100)    NULL,
    RESOURCE_VERSION      VARCHAR(25)     NULL,
    PARENT_ENTITY_TYPE    VARCHAR(40)     NOT NULL,
    PARENT_ENTITY_ID      VARCHAR(100)    NOT NULL,
    UPDATED_ON            VARCHAR(20),
    PRIMARY KEY (METANAME,PARENT_ENTITY_ID)
);
