CREATE TABLE IF NOT EXISTS dti.rt_nos_server
(
    CLOUD_OWNER           VARCHAR(25)  NOT NULL,
    CLOUD_REGION_ID       VARCHAR(20)  NOT NULL,
    TENANT_ID             VARCHAR(150) NOT NULL,
    NOS_SERVER_ID         VARCHAR(150) NOT NULL,
    NOS_SERVER_NAME       VARCHAR(50) NOT NULL,
    VENDOR                VARCHAR(50),
    PROV_STATUS           VARCHAR(20),
    NOS_SERVER_SELFLINK   VARCHAR(4000),
    IN_MAINT              VARCHAR(1),
    RESOURCE_VERSION      VARCHAR(25),
    UPDATED_ON            VARCHAR(20),
    PRIMARY KEY (CLOUD_OWNER, CLOUD_REGION_ID, TENANT_ID, NOS_SERVER_ID)
);
