CREATE TABLE IF NOT EXISTS dti.rt_port_group
(
    INTERFACE_ID            VARCHAR(150) NOT NULL,
    NEUTRON_NETWORK_ID      VARCHAR(150),
    NEUTRON_NETWORK_NAME    VARCHAR(200),
    INTERFACE_ROLE          VARCHAR(25),
    RESOURCE_VERSION        VARCHAR(25),
    PORT_GROUP_ID           VARCHAR(200),
    PORT_GROUP_NAME         VARCHAR(100),
    SWITCH_NAME             VARCHAR(150),
    ORCHESTRATION_STATUS    VARCHAR(25),
    HEAT_STACK_ID           VARCHAR(150),
    MSO_CATALOG_KEY         VARCHAR(200),
    VNF_ID                  VARCHAR(150) NOT NULL,
    UPDATED_ON              VARCHAR(20),
    PRIMARY KEY (INTERFACE_ID,VNF_ID)
);
