CREATE TABLE IF NOT EXISTS dti.rt_p_interface
(
    INTERFACE_NAME          VARCHAR(50) NOT NULL,
    INTERFACE_NAME2			VARCHAR(50),
    SPEED_VALUE             BIGINT,
    SPEED_UNITS             VARCHAR(10),
    PORT_DESCRIPTION        VARCHAR(40),
    RESOURCE_VERSION        VARCHAR(25),
    EQUIPMENT_IDENTIFIER    VARCHAR(100),
    INTERFACE_ROLE          VARCHAR(100),
    INTERFACE_TYPE          VARCHAR(100),
    PROV_STATUS             VARCHAR(20),
    IN_MAINT                VARCHAR(1) NOT NULL DEFAULT 'N',
    INV_STATUS              VARCHAR(20),
    PARENT_ENTITY_ID        VARCHAR(100), 
    PARENT_ENTITY_TYPE      VARCHAR(40),
    SELFLINK               VARCHAR(4000),
    UPDATED_ON              VARCHAR(20),
    PRIMARY KEY (INTERFACE_NAME,PARENT_ENTITY_TYPE,PARENT_ENTITY_ID)
);
