DROP TABLE IF EXISTS dti.rt_process_history CASCADE;
CREATE TABLE dti.rt_process_history
(
        PROCESS_QUEUED_DATETIME	VARCHAR(17) NOT NULL,
	PROCESSED_TIME		VARCHAR(17) NOT NULL,
	NETWORK			VARCHAR(10) NOT NULL,
	VSERVER_NAME		VARCHAR(50) NOT NULL,
        ENTITY			VARCHAR(50) NOT NULL,
        ENTITY_KEY		VARCHAR(200),
	ACTION			VARCHAR(10),
	TIMESTAMP		VARCHAR(14),
        RT_PROCESS_STATUS	VARCHAR(10) NOT NULL,
        UPDATED_ON                VARCHAR(20)
)      ;
