CREATE TABLE IF NOT EXISTS dti.rt_subnet
(
    SUBNET_ID                VARCHAR(150) NOT NULL,
    SUBNET_NAME              VARCHAR(150),
    NEUTRON_SUBNET_ID        VARCHAR(150),
    GATEWAY_ADDRESS          VARCHAR(45),
    NETWORK_START_ADDRESS    VARCHAR(45),
    CIDR_MASK                VARCHAR(20),
    IP_VERSION               VARCHAR(4),
    ORCHESTRATION_STATUS     VARCHAR(25),
    DHCP_ENABLED             VARCHAR(1),
    DHCP_START               VARCHAR(45),
    DHCP_END                 VARCHAR(45),
    RESOURCE_VERSION         VARCHAR(25),
    NETWORK_ID               VARCHAR(100) NOT NULL,
    SUBNET_ROLE              VARCHAR(50),
    IP_ASSIGNMENT_DIRECTION  VARCHAR(50),
    SUBNET_SEQUENCE          VARCHAR(20),
    UPDATED_ON               VARCHAR(20),
    PRIMARY KEY (SUBNET_ID,NETWORK_ID)
);
