CREATE TABLE IF NOT EXISTS dti.rt_service
(
    SERVICE_ID             VARCHAR(150 ) NOT NULL,
    SERVICE_DESCRIPTION    VARCHAR(150) NOT NULL,
    SERVICE_SELFLINK       VARCHAR(4000),
    RESOURCE_VERSION       VARCHAR(25),
    UPDATED_ON             VARCHAR(20),
    PRIMARY KEY (SERVICE_ID)
);
