CREATE TABLE IF NOT EXISTS dti.rt_vlan
(
    VLAN_INTERFACE           VARCHAR(64) NOT NULL,
    VLAN_ID_INNER            DECIMAL(32),
    VLAN_ID_OUTER            DECIMAL(32),
    RESOURCE_VERSION         VARCHAR(25),
    SPEED_VALUE              BIGINT,
    SPEED_UNITS              VARCHAR(10),
    VLAN_DESCRIPTION         VARCHAR(100),
    BACKDOOR_CONNECTION      VARCHAR(25),
    VPN_KEY                  VARCHAR(20),
    ORCHESTRATION_STATUS     VARCHAR(25),
    IN_MAINT                 VARCHAR(1) NOT NULL DEFAULT 'N',
    PROV_STATUS              VARCHAR(20),
    IS_IP_UNNUMBERED         VARCHAR(1) NOT NULL DEFAULT 'N',
    INTERFACE_NAME           VARCHAR(60) NOT NULL,
    GRANDPARENT_ENTITY_TYPE  VARCHAR(60) NOT NULL,
    GRANDPARENT_ENTITY_ID    VARCHAR(150) NOT NULL,
    CLOUD_REGION_TENANT      VARCHAR(200),
    P_INTERFACE_NAME         VARCHAR(50),
    LAG_INTERFACE_NAME       VARCHAR(40),
    UPDATED_ON               VARCHAR(20),
    PRIMARY KEY (VLAN_INTERFACE,INTERFACE_NAME,GRANDPARENT_ENTITY_ID,CLOUD_REGION_TENANT,P_INTERFACE_NAME,LAG_INTERFACE_NAME)
);
