CREATE TABLE IF NOT EXISTS dti.rt_vnf_image
(
    VNF_IMAGE_UUID         VARCHAR(75) NOT NULL,
    APPLICATION            VARCHAR(40) NOT NULL,
    APPLICATION_VENDOR     VARCHAR(50) NOT NULL,
    APPLICATION_VERSION    VARCHAR(250),
    SELFLINK               VARCHAR(4000),
    RESOURCE_VERSION       VARCHAR(25),
    UPDATED_ON             VARCHAR(20),
    PRIMARY KEY (VNF_IMAGE_UUID)
);
