CREATE TABLE IF NOT EXISTS dti.rt_volume
(
    VOLUME_ID           VARCHAR(150) NOT NULL,
    VOLUME_SELFLINK     VARCHAR(4000),
    RESOURCE_VERSION    VARCHAR(25),
    VSERVER_ID          VARCHAR(150) NOT NULL,
    UPDATED_ON          VARCHAR(20),
    PRIMARY KEY (VOLUME_ID,VSERVER_ID)
);
