CREATE TABLE IF NOT EXISTS dti.rt_vpls_pe
(
    EQUIPMENT_NAME      VARCHAR(100)    NOT NULL,
    PROV_STATUS         VARCHAR(10)     NULL,
    IPV4_OAM_ADDRESS    VARCHAR(20)     NULL,
    EQUIPMENT_ROLE      VARCHAR(50)     NULL,
    VLAN_ID_OUTER       VARCHAR(64)     NULL,
    RESOURCE_VERSION    VARCHAR(25)     NULL,
    UPDATED_ON          VARCHAR(20),
    PRIMARY KEY (EQUIPMENT_NAME)
);
