CREATE OR REPLACE VIEW dti.aai_generic_vnf as
select  
	 VNF_ID   ,                    
	 VNF_NAME ,                    
	 VNF_NAME2,                    
	 VNF_TYPE ,                    
	 SERVICE_ID,                   
	 REGIONAL_RESOURCE_ZONE,       
	 PROV_STATUS           ,       
	 OPERATIONAL_STATUS    ,       
	 EQUIPMENT_ROLE        ,       
	 ORCHESTRATION_STATUS  ,       
	 HEAT_STACK_ID         ,       
	 MSO_CATALOG_KEY       ,       
	 MANAGEMENT_OPTION     ,       
	 IPV4_OAM_ADDRESS      ,       
	 IPV4_LOOPBACK0_ADDRESS,       
	 NM_LANV6_ADDRESS      ,       
	 MANAGEMENT_V6_ADDRESS ,       
	 VCPU                  ,       
	 VCPU_UNITS            ,       
	 VMEMORY               ,       
	 VMEMORY_UNITS         ,       
	 VDISK                 ,       
	 VDISK_UNITS           ,       
	 IN_MAINT              ,       
	 IS_CLOSED_LOOP_DISABLED,      
	 RESOURCE_VERSION       ,      
	 SUMMARY_STATUS 	,	
	 ENCRYPTED_ACCESS_FLAG  ,	
	 MODEL_INVARIANT_ID     , 	
	 MODEL_VERSION_ID       , 	
	 MODEL_CUSTOMIZATION_ID ,
	 WIDGET_MODEL_ID        , 	
	 WIDGET_MODEL_VERSION   , 	
	 AS_NUMBER              ,      
	 REGIONAL_RESOURCE_SUBZONE,    
	 NF_TYPE                ,    
	 NF_ROLE                ,    
	 NF_FUNCTION            ,    
	 NF_NAMING_CODE         ,    
	 SELFLINK               
   from dti.rt_generic_vnf;
