CREATE OR REPLACE VIEW dti.rt_l_interface_generic_vnf_v AS
SELECT
l.INTERFACE_NAME,
l.INTERFACE_ROLE,
l.V6_WAN_LINK_IPADDRESS,
l.SELFLINK,
l.INTERFACE_ID,
l.MACADDRESS,
l.NETWORK_NAME,
l.PARENT_ENTITY_TYPE,
l.PARENT_ENTITY_ID,
l.VALIDFROM AS validfrom_l_interface,
g.VNF_ID,
g.VNF_NAME,
g.VNF_NAME2,
g.VNF_TYPE,
g.SERVICE_ID,
g.REGIONAL_RESOURCE_ZONE,
g.PROV_STATUS,
g.OPERATIONAL_STATUS,
g.EQUIPMENT_ROLE,
g.ORCHESTRATION_STATUS,
g.HEAT_STACK_ID,
g.MSO_CATALOG_KEY,
g.MANAGEMENT_OPTION,
g.IPV4_OAM_ADDRESS,
g.IPV4_LOOPBACK0_ADDRESS,
g.NM_LANV6_ADDRESS,
g.MANAGEMENT_V6_ADDRESS,
g.VCPU,
g.VCPU_UNITS,
g.VMEMORY,
g.VMEMORY_UNITS,
g.VDISK,
g.VDISK_UNITS,
g.IN_MAINT,
g.IS_CLOSED_LOOP_DISABLED,
g.VALIDFROM AS validfrom_generic_vnf
FROM dti.rt_l_interface l
INNER JOIN dti.rt_generic_vnf g
ON g.vnf_id = l.parent_entity_id
WHERE l.parent_entity_type = 'generic-vnf'
AND   l.validto IS NULL
AND   g.validto IS NULL;
