dcaeurl: https://git.onap.org/dcaegen2/platform/cli/plain
dcaeuser: aoadapter
onboardingurl: http://dcaemod-onboarding-api:8080/onboarding
onboardinguser: ''
onboardingpass: ''
certfile: /run/certs/cert.pem
dockerregistry: {{ .Values.dockerTargetRegistry }}
dockeruser: {{ .Values.dockerUser }}
dockerpass: '@/run/pass/dpass'
{{ $firstPort := index .Values.service.ports 0 -}}
port: {{ $firstPort.port }}
