// ============LICENSE_START=======================================================
// Copyright (c) 2020 AT&T Intellectual Property. All rights reserved.
// ================================================================================
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ============LICENSE_END=========================================================

package com.att.vcc.inventorycollector.data;

// Generated Feb 3, 2016 5:34:29 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * Vnodelist generated by hbm2java
 * 
 */

/**
 * Database Table name:		VNodeList
 * Java Domain Class Name:	VNodes
 * 
 */
public class VNode implements java.io.Serializable {

	private BigDecimal vnodelistkey;
	private String userid;
	private String validfrom;
	private String validto;
	private String updatedby;
	private String deleteby;
	private String sendtoetl;
	private String nodeName;
	private String nodelevel;
	private String provStatus;
	private String inMaint;
	private String service;
	private String funcCode;
	private String network;
	private String serviceType;
	private String nodeType;
	private String nodeSubType;
	private String clli;
	private String regionZone;
	private String oampIpAddr;
	private String tvspIpAddr;
	private String colNodeName;
	private String colIpAddr;
	private String uuid;
	private String fqdn;
	private String vnfParent;
	private String vsParent;
	private String psParent;
	private String mateNode;
	private String tenantId;
	private String vnfcFuncCode;
	private String dkatService;
	private String dkatNodeType;


	public VNode() {
	}

	public VNode(BigDecimal vnodelistkey, String userid, String validfrom,
			String sendtoetl, String nodeName, String provStatus,
			String inMaint, String service,
			String funcCode, String network, String serviceType,
			String nodeType, String nodeSubType, String oampIpAddr) {
		this.vnodelistkey = vnodelistkey;
		this.userid = userid;
		this.validfrom = validfrom;
		this.sendtoetl = sendtoetl;
		this.nodeName = nodeName;
		this.provStatus = provStatus;
		this.inMaint = inMaint;
		this.service = service;
		this.funcCode = funcCode;
		this.network = network;
		this.serviceType = serviceType;
		this.nodeType = nodeType;
		this.nodeSubType = nodeSubType;
		this.oampIpAddr = oampIpAddr;
	}

	public VNode(BigDecimal vnodelistkey, String userid, String validfrom,
			String validto, String updatedby, String deleteby,
			String sendtoetl, String nodeName, String nodelevel,
			String provStatus, String inMaint, String collect, String alert,
			String service, String funcCode, String network,
			String serviceType, String nodeType, String nodeSubType,
			String clli, String regionZone, String oampIpAddr,
			String tvspIpAddr, String colNodeName, String colIpAddr,
			String uuid, String fqdn, String vnfParent, String vsParent,
			String psParent, String mateNode, String tenantId, String vnfcFuncCode) {
		this.vnodelistkey = vnodelistkey;
		this.userid = userid;
		this.validfrom = validfrom;
		this.validto = validto;
		this.updatedby = updatedby;
		this.deleteby = deleteby;
		this.sendtoetl = sendtoetl;
		this.nodeName = nodeName;
		this.nodelevel = nodelevel;
		this.provStatus = provStatus;
		this.inMaint = inMaint;
		this.service = service;
		this.funcCode = funcCode;
		this.network = network;
		this.serviceType = serviceType;
		this.nodeType = nodeType;
		this.nodeSubType = nodeSubType;
		this.clli = clli;
		this.regionZone = regionZone;
		this.oampIpAddr = oampIpAddr;
		this.tvspIpAddr = tvspIpAddr;
		this.colNodeName = colNodeName;
		this.colIpAddr = colIpAddr;
		this.uuid = uuid;
		this.fqdn = fqdn;
		this.vnfParent = vnfParent;
		this.vsParent = vsParent;
		this.psParent = psParent;
		this.mateNode = mateNode;
		this.tenantId = tenantId;
		this.vnfcFuncCode = vnfcFuncCode;
	}
	
	
	public String toString() {
		
			String str ="\nnodeName=" + this.nodeName + "\n" + 
						"nodelevel=" + this.nodelevel + "\n" + 
						"provStatus=" + this.provStatus + "\n" + 
						"inMaint=" + this.inMaint + "\n" + 
						"service=" + this.service + "\n" + 
						"funcCode=" + this.funcCode + "\n" + 
						"network=" + this.network + "\n" + 
						"serviceType=" + this.serviceType + "\n" + 
						"nodeType=" + this.nodeType + "\n" + 
						"nodeSubType=" + this.nodeSubType + "\n" + 
						"clli=" + this.clli + "\n" + 
						"regionZone=" + this.regionZone + "\n" + 
						"oampIpAddr=" + this.oampIpAddr + "\n" + 
						"tvspIpAddr=" + this.tvspIpAddr + "\n" + 
						"colNodeName=" + this.colNodeName + "\n" + 
						"colIpAddr=" + this.colIpAddr + "\n" + 
						"uuid=" + this.uuid + "\n" + 
						"fqdn=" + this.fqdn + "\n" + 
						"vnfParent=" + this.vnfParent + "\n" + 
						"vsParent=" + this.vsParent + "\n" + 
						"psParent=" + this.psParent + "\n" + 
						"mateNode=" + this.mateNode + "\n" + 
						"tenantId=" + this.tenantId + "\n" + 
						"vnfcFuncCode=" + this.vnfcFuncCode + "\n" + 
						"dkatService=" + this.dkatService + "\n" + 
						"dkatNodeType=" + this.dkatNodeType + "\n";
		
		return str;
	}

	public BigDecimal getVnodelistkey() {
		return this.vnodelistkey;
	}

	public void setVnodelistkey(BigDecimal vnodelistkey) {
		this.vnodelistkey = vnodelistkey;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getValidfrom() {
		return this.validfrom;
	}

	public void setValidfrom(String validfrom) {
		this.validfrom = validfrom;
	}

	public String getValidto() {
		return this.validto;
	}

	public void setValidto(String validto) {
		this.validto = validto;
	}

	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	public String getDeleteby() {
		return this.deleteby;
	}

	public void setDeleteby(String deleteby) {
		this.deleteby = deleteby;
	}

	public String getSendtoetl() {
		return this.sendtoetl;
	}

	public void setSendtoetl(String sendtoetl) {
		this.sendtoetl = sendtoetl;
	}

	public String getNodeName() {
		return this.nodeName;
	}

	public void setNodeName(String nodeName) {
		this.nodeName = nodeName;
	}

	public String getNodelevel() {
		return this.nodelevel;
	}

	public void setNodelevel(String nodelevel) {
		this.nodelevel = nodelevel;
	}

	public String getProvStatus() {
		return this.provStatus;
	}

	public void setProvStatus(String provStatus) {
		this.provStatus = provStatus;
	}

	public String getInMaint() {
		return this.inMaint;
	}

	public void setInMaint(String inMaint) {
		this.inMaint = inMaint;
	}

	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	public String getFuncCode() {
		return this.funcCode;
	}

	public void setFuncCode(String funcCode) {
		this.funcCode = funcCode;
	}

	public String getNetwork() {
		return this.network;
	}

	public void setNetwork(String network) {
		this.network = network;
	}

	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	public String getNodeType() {
		return this.nodeType;
	}

	public void setNodeType(String nodeType) {
		this.nodeType = nodeType;
	}

	public String getNodeSubType() {
		return this.nodeSubType;
	}

	public void setNodeSubType(String nodeSubType) {
		this.nodeSubType = nodeSubType;
	}

	public String getClli() {
		return this.clli;
	}

	public void setClli(String clli) {
		// this.clli = clli;
		
		if ( clli == null || clli.isEmpty() || clli.length() <= 25 ) {
			this.clli = clli;
		} else {
			String s = clli.substring(0, 25);
			this.clli = s;
		}
	}

	public String getRegionZone() {
		return this.regionZone;
	}

	public void setRegionZone(String regionZone) {
		this.regionZone = regionZone;
	}

	public String getOampIpAddr() {
		return this.oampIpAddr;
	}

	public void setOampIpAddr(String oampIpAddr) {
		this.oampIpAddr = oampIpAddr;
	}

	public String getTvspIpAddr() {
		return this.tvspIpAddr;
	}

	public void setTvspIpAddr(String tvspIpAddr) {
		this.tvspIpAddr = tvspIpAddr;
	}

	public String getColNodeName() {
		return this.colNodeName;
	}

	public void setColNodeName(String colNodeName) {
		this.colNodeName = colNodeName;
	}

	public String getColIpAddr() {
		return this.colIpAddr;
	}

	public void setColIpAddr(String colIpAddr) {
		this.colIpAddr = colIpAddr;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getFqdn() {
		return this.fqdn;
	}

	public void setFqdn(String fqdn) {
		this.fqdn = fqdn;
	}

	public String getVnfParent() {
		return this.vnfParent;
	}

	public void setVnfParent(String vnfParent) {
		this.vnfParent = vnfParent;
	}

	public String getVsParent() {
		return this.vsParent;
	}

	public void setVsParent(String vsParent) {
		this.vsParent = vsParent;
	}

	public String getPsParent() {
		return this.psParent;
	}

	public void setPsParent(String psParent) {
		this.psParent = psParent;
	}

	public String getMateNode() {
		return this.mateNode;
	}

	public void setMateNode(String mateNode) {
		this.mateNode = mateNode;
	}
	
	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	public String getVnfcFuncCode() {
		return this.vnfcFuncCode;
	}

	public void setVnfcFuncCode(String vnfcFuncCode) {
		this.vnfcFuncCode = vnfcFuncCode;
	}

	public String getDkatService() {
		return dkatService;
	}

	public void setDkatService(String dkatService) {
		this.dkatService = dkatService;
	}

	public String getDkatNodeType() {
		return dkatNodeType;
	}

	public void setDkatNodeType(String dkatNodeType) {
		this.dkatNodeType = dkatNodeType;
	}

}
