CREATE TABLE IF NOT EXISTS dti.narad_cable
(
		PHYSICAL_LOCATION_ID VARCHAR(50)	 NOT NULL,
		CABLE_NAME VARCHAR(50)	 NOT NULL,
		CABLE_TYPE VARCHAR(50)	 NOT NULL,
		RESOURCE_VERSION VARCHAR(25),
		UPDATED_ON                VARCHAR(20),
		PRIMARY KEY (PHYSICAL_LOCATION_ID, CABLE_NAME)
);
