CREATE TABLE IF NOT EXISTS dti.narad_rack
(
	PHYSICAL_LOCATION_ID VARCHAR(50)	 NOT NULL,
	RACK_NAME VARCHAR(50)	 NOT NULL,
	RACK_TYPE VARCHAR(50)	 NOT NULL,
	RACK_LOCATION VARCHAR(50)	 NOT NULL,
	RACK_POSITION VARCHAR(50),
	RACK_POWER_DIVERSITY VARCHAR(20),
	RESOURCE_VERSION VARCHAR(25),
	UPDATED_ON                VARCHAR(20),
	PRIMARY KEY (PHYSICAL_LOCATION_ID, RACK_NAME)
);
