CREATE TABLE IF NOT EXISTS dti.narad_chassis
(
		CHASSIS_NAME VARCHAR(50)	 NOT NULL,
		CHASSIS_TYPE VARCHAR(500)	 NOT NULL,
		CHASSIS_ROLE VARCHAR(50)	 NOT NULL,
		SERIAL_NUMBER VARCHAR(50),
		ASSET_TAG VARCHAR(50),
		RESOURCE_VERSION VARCHAR(25),
		UPDATED_ON                VARCHAR(20),
		PRIMARY KEY (CHASSIS_NAME)
);
